exynos: Remove unneeded DWMMC_MAX_CH_NUM setting
This sets the maximum number of DWMMC ports. We could adjust the code to
remove any such limitation, but for now let's go with a larger maximum. The
impact is only a few more words of stack space during mmc init. The actual
number of active ports is set by the device tree anyway, so this settings
really has no purpose.

BUG=chrome-os-partner:18329
TEST=manual
Boot on pit and see that mmc still seems to work:

Peach # mmc dev 0
mmc0(part 0) is current device
Peach # mmcinfo
Device: EXYNOS DWMMC
Manufacturer ID: 15
OEM: 100
Name: MAG2G
Tran Speed: 52000000
Rd Block Len: 512
MMC version 4.5
High Capacity: Yes
Capacity: 14.6 GiB
Bus Width: 8-bit
Peach # mmc part

Partition Map for MMC device 0  --   Partition Type: EFI

Part	Start LBA	End LBA		Name
	Attributes
	Type UUID
	Partition UUID
  1	0x00845000	0x01d16fff	"STATE"
	attrs:	0x0000000000000000
	type:	ebd0a0a2-b9e5-4433-87c0-68b6b72699c7
	uuid:	5c39a473-b941-df4a-922d-a83734ea4801
  2	0x00005000	0x0000cfff	"KERN-A"
	attrs:	0x0161000000000000
	type:	fe3a2a5d-4f32-41a7-b725-accc3285a309
	uuid:	a586e8c0-b863-2844-a541-5fff01340a38
  3	0x00445000	0x00844fff	"ROOT-A"
	attrs:	0x0000000000000000
	type:	3cb8e202-3b7e-47dd-8a3c-7ff2a13cfcec
	uuid:	fc9ffab1-c8f2-ae43-8b62-7e3af84a0bb2
  4	0x0000d000	0x00014fff	"KERN-B"
	attrs:	0x00f0000000000000
	type:	fe3a2a5d-4f32-41a7-b725-accc3285a309
	uuid:	70c638a9-832d-5840-9c8f-49ff46bf5a9f
  5	0x00045000	0x00444fff	"ROOT-B"
	attrs:	0x0000000000000000
	type:	3cb8e202-3b7e-47dd-8a3c-7ff2a13cfcec
	uuid:	b3748c42-bf8f-da4f-bf8e-2999eab4ee6f
  6	0x00004040	0x00004040	"KERN-C"
	attrs:	0x00f0000000000000
	type:	fe3a2a5d-4f32-41a7-b725-accc3285a309
	uuid:	ec38564a-2b77-e849-a2ac-5fb0d6e39646
  7	0x00004041	0x00004041	"ROOT-C"
	attrs:	0x0000000000000000
	type:	3cb8e202-3b7e-47dd-8a3c-7ff2a13cfcec
	uuid:	c7979e21-e5f7-b240-940c-65645aac1799
  8	0x00015000	0x0001cfff	"OEM"
	attrs:	0x0000000000000000
	type:	ebd0a0a2-b9e5-4433-87c0-68b6b72699c7
	uuid:	ccd120a3-2bfc-cd41-9e2f-b1e15e40d4dd
  9	0x00004042	0x00004042	"reserved"
	attrs:	0x0000000000000000
	type:	2e0a753d-9e48-43b0-8337-b15192cb1b5e
	uuid:	04c4ab56-b5bc-0247-bee9-d9ba5ca4284d
 10	0x00004043	0x00004043	"reserved"
	attrs:	0x0000000000000000
	type:	2e0a753d-9e48-43b0-8337-b15192cb1b5e
	uuid:	63eb2833-1668-964a-a698-8bc7280da48f
 11	0x00000040	0x0000403f	"RWFW"
	attrs:	0x0000000000000000
	type:	cab6e88e-abf3-4102-a07a-d4bb9be3c1d3
	uuid:	2382c95a-5b17-1449-88c3-4f9ede136fec
 12	0x0003d000	0x00044fff	"EFI-SYSTEM"
	attrs:	0x0000000000000000
	type:	c12a7328-f81f-11d2-ba4b-00a0c93ec93b
	uuid:	61a2453e-bc3d-ef4c-9d22-cd8227e438c0
Peach # mmc dev 1
ERROR: v7_dcache_inval_range - stop address is not aligned - 0xff93c808
mmc1 is current device
Peach # mmcindo
Unknown command 'mmcindo' - try 'help'
Peach # mmcinfo
Device: EXYNOS DWMMC
Manufacturer ID: 3
OEM: 5344
Name: SU04G
Tran Speed: 50000000
Rd Block Len: 512
SD version 3.0
High Capacity: Yes
Capacity: 3.7 GiB
Bus Width: 4-bit
Peach #

Change-Id: Iff8ef29e8b788f2b93f774a2e156a00ec688f3ad
Signed-off-by: Simon Glass <sjg@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/59373
Reviewed-by: Che-Liang Chiou <clchiou@chromium.org>