elog: enforce elog header size to be divisible by 4
Bad things will happen in spl_boot.c if the elog header size ever
changes from being divisible by 4.

This patch adds a compile time check casing an error if the
requirement is not met.

BRANCH=ToT
BUG=chrome-os-partner:16132
TEST=manual

  . modified reserved field in the header to be 3 bytes in size, tried
    building a pit image. Got the following compilation error:

   In file included from board_r.c:38:0:
   /mnt/host/source/src/third_party/u-boot/files/include/elog.h:156:7: error: size of array 'a1' is negative

Change-Id: If7bc79f09fefea242c9da371680fe29c3a99a754
Signed-off-by: Vadim Bendebury <vbendeb@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/168477
Reviewed-by: Gabe Black <gabeblack@chromium.org>
Reviewed-by: Simon Glass <sjg@chromium.org>
Commit-Queue: Vadim Bendebury <vbendeb@gmail.com>
Tested-by: Vadim Bendebury <vbendeb@gmail.com>
Reviewed-on: https://chromium-review.googlesource.com/186476
Reviewed-by: Doug Anderson <dianders@chromium.org>